/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as RoleRouteImport } from './routes/role'
import { Route as RegistersInstallationRouteImport } from './routes/registers/installation'
import { Route as RegistersSalesRouteImport } from './routes/registers/sales'
import { Route as RegistersSqcRouteImport } from './routes/registers/sqc'
import { Route as RegistersStockRouteImport } from './routes/registers/stock'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersInstallationRoute = RegistersInstallationRouteImport.update({
  id: '/registers/installation',
  path: '/registers/installation',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersSalesRoute = RegistersSalesRouteImport.update({
  id: '/registers/sales',
  path: '/registers/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersSqcRoute = RegistersSqcRouteImport.update({
  id: '/registers/sqc',
  path: '/registers/sqc',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersStockRoute = RegistersStockRouteImport.update({
  id: '/registers/stock',
  path: '/registers/stock',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/role': typeof RoleRoute
  '/registers/installation': typeof RegistersInstallationRoute
  '/registers/sales': typeof RegistersSalesRoute
  '/registers/sqc': typeof RegistersSqcRoute
  '/registers/stock': typeof RegistersStockRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/role': typeof RoleRoute
  '/registers/installation': typeof RegistersInstallationRoute
  '/registers/sales': typeof RegistersSalesRoute
  '/registers/sqc': typeof RegistersSqcRoute
  '/registers/stock': typeof RegistersStockRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/role': typeof RoleRoute
  '/registers/installation': typeof RegistersInstallationRoute
  '/registers/sales': typeof RegistersSalesRoute
  '/registers/sqc': typeof RegistersSqcRoute
  '/registers/stock': typeof RegistersStockRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/role'
    | '/registers/installation'
    | '/registers/sales'
    | '/registers/sqc'
    | '/registers/stock'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/role'
    | '/registers/installation'
    | '/registers/sales'
    | '/registers/sqc'
    | '/registers/stock'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/role'
    | '/registers/installation'
    | '/registers/sales'
    | '/registers/sqc'
    | '/registers/stock'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  RoleRoute: typeof RoleRoute
  RegistersInstallationRoute: typeof RegistersInstallationRoute
  RegistersSalesRoute: typeof RegistersSalesRoute
  RegistersSqcRoute: typeof RegistersSqcRoute
  RegistersStockRoute: typeof RegistersStockRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers/installation': {
      id: '/registers/installation'
      path: '/registers/installation'
      fullPath: '/registers/installation'
      preLoaderRoute: typeof RegistersInstallationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers/sales': {
      id: '/registers/sales'
      path: '/registers/sales'
      fullPath: '/registers/sales'
      preLoaderRoute: typeof RegistersSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers/sqc': {
      id: '/registers/sqc'
      path: '/registers/sqc'
      fullPath: '/registers/sqc'
      preLoaderRoute: typeof RegistersSqcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers/stock': {
      id: '/registers/stock'
      path: '/registers/stock'
      fullPath: '/registers/stock'
      preLoaderRoute: typeof RegistersStockRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  RoleRoute: RoleRoute,
  RegistersInstallationRoute: RegistersInstallationRoute,
  RegistersSalesRoute: RegistersSalesRoute,
  RegistersSqcRoute: RegistersSqcRoute,
  RegistersStockRoute: RegistersStockRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
